version: "2"
services:
  hapifhir:
    image: openlmis/hapifhir
    links:
      - db
      - log
    env_file: .env
  db:
    image: openlmis/postgres:9.6
    env_file: .env
  log:
    image: openlmis/rsyslog:1
    volumes:
      - '../logs/hapifhir-service:/var/log'
